// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code. Version 3.6.0.0
//    <NameSpace>Keygen2012</NameSpace><Collection>List</Collection><codeType>CSharp</codeType><EnableDataBinding>False</EnableDataBinding><EnableLazyLoading>False</EnableLazyLoading><TrackingChangesEnable>False</TrackingChangesEnable><GenTrackingClasses>False</GenTrackingClasses><HidePrivateFieldInIDE>False</HidePrivateFieldInIDE><EnableSummaryComment>False</EnableSummaryComment><VirtualProp>False</VirtualProp><PascalCase>False</PascalCase><BaseClassName>EntityBase</BaseClassName><IncludeSerializeMethod>False</IncludeSerializeMethod><UseBaseClass>False</UseBaseClass><GenBaseClass>False</GenBaseClass><GenerateCloneMethod>False</GenerateCloneMethod><GenerateDataContracts>False</GenerateDataContracts><CodeBaseTag>Net20</CodeBaseTag><SerializeMethodName>Serialize</SerializeMethodName><DeserializeMethodName>Deserialize</DeserializeMethodName><SaveToFileMethodName>SaveToFile</SaveToFileMethodName><LoadFromFileMethodName>LoadFromFile</LoadFromFileMethodName><GenerateXMLAttributes>False</GenerateXMLAttributes><OrderXMLAttrib>False</OrderXMLAttrib><EnableEncoding>False</EnableEncoding><AutomaticProperties>False</AutomaticProperties><GenerateShouldSerialize>False</GenerateShouldSerialize><DisableDebug>False</DisableDebug><PropNameSpecified>Default</PropNameSpecified><Encoder>UTF8</Encoder><CustomUsings></CustomUsings><ExcludeIncludedTypes>False</ExcludeIncludedTypes><InitializeFields>All</InitializeFields><GenerateAllTypes>True</GenerateAllTypes>
//  </auto-generated>
// ------------------------------------------------------------------------------
namespace Keygen2012
{
    using System;
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System.Collections;
    using System.Xml.Schema;
    using System.ComponentModel;
    using System.Collections.Generic;

   
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://schemas.microsoft.com/pag/cab-profile/2.0", IsNullable = false)]
    public partial class SolutionProfile
    {
        
        private List<Section> sectionField;
        
        public SolutionProfile()
        {
            this.sectionField = new List<Section>();
        }

        [System.Xml.Serialization.XmlElementAttribute("Section")]
        public List<Section> Section
        {
            get
            {
                return this.sectionField;
            }
            set
            {
                this.sectionField = value;
            }
        }
    }


    public partial class Section
    {
        
        private Dependencies dependenciesField;
        
        private List<SolutionProfileSectionModuleInfo> modulesField;
        
        private string nameField;
        
        public Section()
        {
            this.modulesField = new List<SolutionProfileSectionModuleInfo>();
            this.dependenciesField = new Dependencies();
        }
        
        public Dependencies Dependencies
        {
            get
            {
                return this.dependenciesField;

            }
            set
            {
                this.dependenciesField = value;
            }
        }
        
        [System.Xml.Serialization.XmlArrayItemAttribute("ModuleInfo", IsNullable=false)]
        public List<SolutionProfileSectionModuleInfo> Modules
        {
            get
            {
                return this.modulesField;
            }
            set
            {
                this.modulesField = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
    }


    public partial class Dependencies
    {
        
        private List<Dependency> dependencyField;
        
        private List<string> textField;
        
        public Dependencies()
        {
            this.textField = new List<string>();
            this.dependencyField = new List<Dependency>();
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Dependency")]
        public List<Dependency> Dependency
        {
            get
            {
                return this.dependencyField;
            }
            set
            {
                this.dependencyField = value;
            }
        }
        
        [System.Xml.Serialization.XmlTextAttribute()]
        public List<string> Text
        {
            get
            {
                return this.textField;
            }
            set
            {
                this.textField = value;
            }
        }
    }

  
    public partial class Dependency
    {
        
        private string nameField;
          [System.Xml.Serialization.XmlAttribute("name")]
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
    }

    public partial class SolutionProfileSectionModuleInfo
    {
        
        private string assemblyFileField;

          [System.Xml.Serialization.XmlAttribute("AssemblyFile")]
        public string AssemblyFile
        {
            get
            {
                return this.assemblyFileField;
            }
            set
            {
                this.assemblyFileField = value;
            }
        }
    }
}
